
[settings]
experimental = true

[tools]
"cargo:p1rallels/codemapper" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:chrome-devtools-mcp" = "0.10.2"
"npm:gh-actions-language-server" = "0.0.3"
"npm:mcporter" = "latest"
"npm:surf-cli" = "latest"
"ubi:mfontanini/presenterm" = "0.15.1"
"ubi:scottmckendry/pokemon-go-colorscripts" = "0.3.1"
act="0.2.31"
actionlint="1.6.20"
ast-grep = "0.40.0"
awscli="2.7.9"
bat="0.22.1"
btop = "latest"
bun = "latest"
cmake="3.29.2"
fzf="0.34.0"
github-cli= "2.83.0"
glow = "latest"
jq="1.7.1"
lazygit="0.42.0"
neovim = "0.11.5"
python = "3.11"
ripgrep="13.0.0"
rust= "1.92.0"
shellcheck="0.9.0"
shfmt="3.6.0"
starship = "1.24.0"
uv = "0.6.8"
"github:cantino/mcfly" = "latest"
node = "lts"
bitwarden = "latest"
"github:moonrepo/moon" = "2.0.4"
"github:moonrepo/proto" = "0.55.4"
